"""Visual sanity-check tools for Ground Truth mask verification.

Overlays GT contours, bounding boxes, and category labels onto original
images to verify mask decoding accuracy. Outputs are saved to disk for
human inspection.

Typical usage:
    >>> from src.utils.visualization import debug_visualize
    >>> saved = debug_visualize(dataset, output_dir="output/data", sample_count=10)
    >>> print(f"Saved {len(saved)} data-layer preview images")
"""

from __future__ import annotations

import logging
import random
from pathlib import Path
from typing import TYPE_CHECKING

import cv2
import numpy as np

if TYPE_CHECKING:
    from src.data.loader import ImageRecord

logger = logging.getLogger(__name__)

# Color palette — HSV hue-spaced for maximum visual distinction
_CATEGORY_COLORS: dict[str, tuple[int, int, int]] = {}


def _get_category_color(category: str) -> tuple[int, int, int]:
    """Return a deterministic BGR color for a given category name.

    Colors are generated by hashing the category name into HSV hue space,
    providing high contrast between different categories.

    Args:
        category: Animal category name (e.g., ``"dog"``).

    Returns:
        BGR color tuple suitable for OpenCV drawing functions.
    """
    if category not in _CATEGORY_COLORS:
        hue = (hash(category) % 180)  # OpenCV HSV hue range: 0-179
        hsv = np.array([[[hue, 220, 230]]], dtype=np.uint8)
        bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
        color = tuple(int(c) for c in bgr[0, 0])
        _CATEGORY_COLORS[category] = color
    return _CATEGORY_COLORS[category]


def debug_visualize(
    dataset: list[ImageRecord],
    output_dir: str = "output/data",
    sample_count: int = 10,
    seed: int = 42,
) -> list[str]:
    """Randomly sample images from dataset and overlay GT annotations.

    For each sampled image, draws:
        - Filled semi-transparent contours (per-category color).
        - Bounding boxes with category labels.
        - Image ID watermark in the top-left corner.

    Args:
        dataset: Output from :meth:`COCODataLoader.load_filtered_dataset`.
        output_dir: Directory to save annotated images.
        sample_count: Number of images to sample. Clamped to dataset size.
        seed: Random seed for reproducible sampling.

    Returns:
        List of absolute paths to saved data-layer preview images.

    Raises:
        FileNotFoundError: An original image file does not exist.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Clamp sample count
    sample_count = min(sample_count, len(dataset))
    if sample_count == 0:
        logger.warning("Dataset is empty, cannot generate visualization samples.")
        return []

    rng = random.Random(seed)
    samples = rng.sample(dataset, sample_count)

    saved_paths: list[str] = []

    for record in samples:
        image_path = Path(record["image_path"])
        if not image_path.is_file():
            raise FileNotFoundError(f"Original image not found: {image_path}")

        image = cv2.imread(str(image_path))
        if image is None:
            logger.error("Failed to read image: %s", image_path)
            continue

        overlay = image.copy()

        for ann in record["annotations"]:
            color = _get_category_color(ann["category"])

            # Draw filled contours on overlay (semi-transparent)
            cv2.drawContours(overlay, ann["contours"], -1, color, cv2.FILLED)

            # Draw bounding box
            x, y, w, h = [int(v) for v in ann["bbox"]]
            cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)

            # Draw category label
            label = f"{ann['category']} (#{ann['id']})"
            font_scale = 0.5
            thickness = 1
            (text_w, text_h), baseline = cv2.getTextSize(
                label, cv2.FONT_HERSHEY_SIMPLEX, font_scale, thickness
            )
            # Label background
            cv2.rectangle(
                image,
                (x, y - text_h - baseline - 4),
                (x + text_w + 4, y),
                color,
                cv2.FILLED,
            )
            cv2.putText(
                image,
                label,
                (x + 2, y - baseline - 2),
                cv2.FONT_HERSHEY_SIMPLEX,
                font_scale,
                (255, 255, 255),
                thickness,
                cv2.LINE_AA,
            )

        # Blend overlay (contours) with original image
        alpha = 0.35
        image = cv2.addWeighted(overlay, alpha, image, 1 - alpha, 0)

        # Image ID watermark
        img_id_text = f"ID: {record['image_id']}"
        cv2.putText(
            image,
            img_id_text,
            (10, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0, 255, 255),
            2,
            cv2.LINE_AA,
        )

        # Save
        out_file = output_path / f"data_{record['image_id']}.jpg"
        cv2.imwrite(str(out_file), image)
        saved_paths.append(str(out_file))
        logger.debug("Saved data layer visualization images: %s", out_file)

    logger.info(
        "Visualization sampling complete: %d/%d images saved to %s",
        len(saved_paths),
        sample_count,
        output_path,
    )
    return saved_paths
